from torch.utils.tensorboard import SummaryWriter


class Logger:
    def __init__(self, log_dir):
        self.writer = SummaryWriter(log_dir=log_dir)

    def log(self, epoch, train_loss, val_loss, metrics):
        self.writer.add_scalar('Loss/train', train_loss, epoch)
        self.writer.add_scalar('Loss/val', val_loss, epoch)
        for name, value in metrics.items():
            self.writer.add_scalar(f'Metrics/{name}', value, epoch)

# To acess the log files generated by tensorboard, run the following command in the terminal:
# tensorboard --logdir=runs
# Then open the browser and go to the following link:
# http://localhost:6006/
